### ISSUE TITLE
Align Dashboard and Widgets with design specs

### ISSUE THREAD

**Issue by krschau** [microsoft/devhome#1460]
### Provide a description of requested docs changes

Small changes need to be made to align with design specs.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/devhome/pull/1461
- [ ] https://github.com/microsoft/devhomegithubextension/pull/209
- [ ] https://github.com/microsoft/devhome/pull/1467
```
