### ISSUE TITLE
Allow user to search for repos when cloning

### ISSUE THREAD

**Issue by krschau** [microsoft/devhome#2444]
### Suggested new feature or improvement

User can search for repos, and Dev Home and the extensions can communicate the request and results.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/devhome/issues/2003
- [ ] https://github.com/microsoft/devhome/pull/2245
- [ ] https://github.com/microsoft/devhome/pull/2443
- [ ] https://github.com/microsoft/DevHomeAzureExtension/pull/136
- [ ] https://github.com/microsoft/DevHomeAzureExtension/pull/141
```
