### ISSUE TITLE
Update Dev Home to use WindowsAppSDK 1.6

### ISSUE THREAD

**Issue by krschau** [microsoft/devhome#3798]
Besides the change in Dev Home, there are dependencies:
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/AdaptiveCards/issues/9001
- [ ] https://github.com/microsoft/PowerToys/pull/34622
- [ ] https://github.com/CommunityToolkit/Windows/pull/457
```
