### ISSUE TITLE
MVVM Toolkit improvements

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/devhome#841]
### Suggested new feature or improvement

As discussed at the Dev Home booth at Build, there's a few log hanging fruits with the MVVM Toolkit here:
```[tasklist]
### Tasks
- [x] https://github.com/microsoft/devhome/pull/842
- [ ] https://github.com/microsoft/devhome/pull/843
- [ ] https://github.com/microsoft/devhome/pull/844
```

For (1), the main advantages of this updates are:
- The source generators are **massively** faster and more efficient
- There's new analyzers to help detect bugs
- There's new features that can be used in the future

The full changelog for the two releases are here:
- [Announcing .NET Community Toolkit 8.1](https://devblogs.microsoft.com/dotnet/announcing-the-dotnet-community-toolkit-810/)
- [Announcing .NET Community Toolkit 8.2](https://devblogs.microsoft.com/dotnet/announcing-the-dotnet-community-toolkit-820/)

For (2) and (3), mostly:
- If messaging features aren't used (which is the case here), using `ObservableRecipient` is just wasteful.
- For those properties/commands, using the source generators just makes the code less verbose and error prone.

**Comment by crutkas** [comment]
all are checked in

**Comment by Sergio0694** [comment]
Awesome! Thank you for the help merging the PRs Clint! Will close this then 🎉
